import './globals.css'
import { Montserrat } from 'next/font/google'

const Mont = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'footer',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Mont.className}>
        {children}</body>
    </html>
  )
}
